# Generated by Django 4.1.2 on 2022-10-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vatable",
            field=models.BooleanField(default=True),
        ),
    ]
