# Generated by Django 4.1.2 on 2022-11-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_product_created_at_product_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
