# Generated by Django 4.1.2 on 2022-12-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_category_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="current_stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="opening_stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="purchased_stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="sold_stock",
            field=models.IntegerField(default=0),
        ),
    ]
