# Generated by Django 4.1.2 on 2022-10-26 05:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(auto_now=True)),
                ("is_credit", models.BooleanField(default=False)),
                (
                    "closing_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SI", "Sales Invoice"),
                            ("SR", "Sales Return"),
                            ("PI", "Purchase Invoice"),
                            ("PR", "Purchase Return"),
                            ("RV", "Receipt Voucher"),
                            ("PV", "Payment Voucher"),
                            ("JV", "Journal Voucher"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CAPITAL", "Capital"),
                            ("FIXED_ASSET", "Fixed Asset"),
                            ("CURRENT_ASSSET", "Current Asset"),
                            ("LOAN_AND_ADVANCE", "Loan and Advance"),
                            ("CASH_AND_BANK", "Cash and Bank"),
                            ("INCOME", "Income"),
                            ("LIABILITY", "Liability"),
                            ("EXPENSE", "Expense"),
                            ("CUSTOMER", "Customer"),
                            ("VENDOR", "Vendor"),
                            ("CUSTOMER_AND_VENDOR", "Customer and Vendor"),
                        ],
                        default="CUSTOMER",
                        max_length=255,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "closing_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("entries", models.ManyToManyField(blank=True, to="audit.entry")),
            ],
        ),
    ]
