# Generated by Django 4.1.2 on 2022-10-26 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="related_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.customer",
            ),
        ),
    ]
