# Generated by Django 4.1.2 on 2022-11-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0006_alter_entry_closing_balance_alter_entryitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
