# Generated by Django 4.1.2 on 2022-12-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0007_ledger_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="date",
            field=models.DateField(),
        ),
    ]
