# Generated by Django 4.1.4 on 2022-12-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0008_alter_entry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
